import { TableHTMLAttributes } from "react";
import { tableHeading } from "./types";

export const headings: tableHeading[] = [
  { title: "First Name", data: "firstName" },
  { title: "Last Name", data: "lastName" },
  { title: "Start Date", data: "startDate" },
  { title: "Department", data: "department" },
  { title: "Date of Birth", data: "dateOfBirth" },
  { title: "Street", data: "street" },
  { title: "City", data: "city" },
  { title: "State", data: "state" },
  { title: "Zip Code", data: "zipCode" },
  { title: "Test nombres", data: "testNumber" },
  { title: "Test booléens", data: "testBoolean" },
];

export const attributesTestNothing: TableHTMLAttributes<any> = {
  id: "table",
  className: undefined,
  style: undefined,
};

export const attributesTestAll: TableHTMLAttributes<any> = {
  id: "table-test-all",
  className: "",
  style: {
    backgroundColor: "white",
  },
};

export const attributesTestTheme: TableHTMLAttributes<any> = {
  id: "table-test-all",
  className: "data-table-classic",
  style: {},
};

export const dataTest: Record<string, any>[] = [
  {
    firstName: "Bob",
    lastName: "Martinez",
    dateOfBirth: "1988-09-18",
    startDate: "2005-12-29",
    street: "66 avenue des champs",
    city: "new york",
    state: "Germany",
    zipCode: "42766",
    department: "department2",
    testNumber: 90,
    testBoolean: false,
  },
  {
    firstName: "David",
    lastName: "Jones",
    dateOfBirth: "2007-11-19",
    startDate: "2024-03-16",
    street: "57 main street",
    city: "lacaune",
    state: "France",
    zipCode: "17198",
    department: "department2",
    testNumber: 62,
    testBoolean: true,
  },
  {
    firstName: "John",
    lastName: "Jones",
    dateOfBirth: "1963-12-13",
    startDate: "1983-02-27",
    street: "29 main street",
    city: "tombouctou",
    state: "USA",
    zipCode: "42075",
    department: "department1",
    testNumber: 65,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Doe",
    dateOfBirth: "2001-09-19",
    startDate: "2021-08-19",
    street: "57 main street",
    city: "paris",
    state: "Japan",
    zipCode: "92767",
    department: "department2",
    testNumber: 87,
    testBoolean: false,
  },
  {
    firstName: "Jane",
    lastName: "Garcia",
    dateOfBirth: "1998-09-30",
    startDate: "2015-03-11",
    street: "47 rue du griffoul",
    city: "tombouctou",
    state: "France",
    zipCode: "75894",
    department: "department4",
    testNumber: 23,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Doe",
    dateOfBirth: "1994-04-17",
    startDate: "2012-02-12",
    street: "7 main street",
    city: "berlin",
    state: "Spain",
    zipCode: "99855",
    department: "department2",
    testNumber: 92,
    testBoolean: false,
  },
  {
    firstName: "Hugo",
    lastName: "Jones",
    dateOfBirth: "1971-07-29",
    startDate: "1988-02-09",
    street: "16 high street",
    city: "castres",
    state: "Mali",
    zipCode: "57133",
    department: "department1",
    testNumber: 48,
    testBoolean: false,
  },
  {
    firstName: "John",
    lastName: "Johnson",
    dateOfBirth: "1952-10-10",
    startDate: "1968-11-15",
    street: "29 main street",
    city: "lacaune",
    state: "Japan",
    zipCode: "81203",
    department: "department2",
    testNumber: 63,
    testBoolean: true,
  },
  {
    firstName: "David",
    lastName: "Doe",
    dateOfBirth: "1970-03-08",
    startDate: "1986-07-12",
    street: "57 boulevard saint-germain",
    city: "castres",
    state: "France",
    zipCode: "72033",
    department: "department2",
    testNumber: 81,
    testBoolean: false,
  },
  {
    firstName: "Hugo",
    lastName: "Brown",
    dateOfBirth: "1953-04-23",
    startDate: "1969-09-28",
    street: "44 main street",
    city: "tombouctou",
    state: "Japan",
    zipCode: "15935",
    department: "department3",
    testNumber: 63,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Miller",
    dateOfBirth: "1953-10-20",
    startDate: "1971-07-19",
    street: "60 main street",
    city: "london",
    state: "France",
    zipCode: "64665",
    department: "department2",
    testNumber: 15,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Johnson",
    dateOfBirth: "2003-05-14",
    startDate: "2020-08-25",
    street: "35 main street",
    city: "madrid",
    state: "France",
    zipCode: "81416",
    department: "department4",
    testNumber: 26,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Martinez",
    dateOfBirth: "2005-10-21",
    startDate: "2025-04-10",
    street: "80 rue du griffoul",
    city: "castres",
    state: "Japan",
    zipCode: "49473",
    department: "department4",
    testNumber: 13,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Johnson",
    dateOfBirth: "1960-06-24",
    startDate: "1980-06-26",
    street: "13 boulevard saint-germain",
    city: "tokyo",
    state: "USA",
    zipCode: "71994",
    department: "department1",
    testNumber: 11,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Doe",
    dateOfBirth: "1974-06-04",
    startDate: "1991-12-07",
    street: "93 boulevard saint-germain",
    city: "dakar",
    state: "Mali",
    zipCode: "79587",
    department: "department4",
    testNumber: 41,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    dateOfBirth: "2006-12-16",
    startDate: "2023-01-29",
    street: "89 rue du griffoul",
    city: "london",
    state: "UK",
    zipCode: "32283",
    department: "department1",
    testNumber: 82,
    testBoolean: false,
  },
  {
    firstName: "John",
    lastName: "Brown",
    dateOfBirth: "1951-05-24",
    startDate: "1968-06-25",
    street: "49 high street",
    city: "new york",
    state: "France",
    zipCode: "13477",
    department: "department4",
    testNumber: 81,
    testBoolean: true,
  },
  {
    firstName: "Frank",
    lastName: "Smith",
    dateOfBirth: "1969-12-13",
    startDate: "1990-02-25",
    street: "44 high street",
    city: "castres",
    state: "Japan",
    zipCode: "49862",
    department: "department2",
    testNumber: 11,
    testBoolean: false,
  },
  {
    firstName: "Alice",
    lastName: "Doe",
    dateOfBirth: "1999-04-06",
    startDate: "2019-11-14",
    street: "76 avenue des champs",
    city: "lacaune",
    state: "France",
    zipCode: "57233",
    department: "department1",
    testNumber: 65,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Brown",
    dateOfBirth: "2001-10-18",
    startDate: "2020-05-17",
    street: "55 rue du griffoul",
    city: "dakar",
    state: "Japan",
    zipCode: "21713",
    department: "department4",
    testNumber: 39,
    testBoolean: true,
  },
  {
    firstName: "Frank",
    lastName: "Davis",
    dateOfBirth: "1974-01-05",
    startDate: "1993-10-28",
    street: "85 rue du griffoul",
    city: "berlin",
    state: "UK",
    zipCode: "27939",
    department: "department1",
    testNumber: 72,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Doe",
    dateOfBirth: "1971-03-23",
    startDate: "1989-02-01",
    street: "38 boulevard saint-germain",
    city: "tokyo",
    state: "Mali",
    zipCode: "78715",
    department: "department3",
    testNumber: 66,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Jones",
    dateOfBirth: "1983-03-13",
    startDate: "2003-05-24",
    street: "40 rue du griffoul",
    city: "dakar",
    state: "France",
    zipCode: "13288",
    department: "department2",
    testNumber: 34,
    testBoolean: false,
  },
  {
    firstName: "Hugo",
    lastName: "Davis",
    dateOfBirth: "1986-06-08",
    startDate: "2003-04-15",
    street: "63 high street",
    city: "lacaune",
    state: "Senegal",
    zipCode: "50012",
    department: "department4",
    testNumber: 89,
    testBoolean: false,
  },
  {
    firstName: "Frank",
    lastName: "Doe",
    dateOfBirth: "1992-02-24",
    startDate: "2009-01-18",
    street: "85 high street",
    city: "dakar",
    state: "Spain",
    zipCode: "33048",
    department: "department3",
    testNumber: 61,
    testBoolean: false,
  },
  {
    firstName: "Frank",
    lastName: "Jones",
    dateOfBirth: "1971-10-31",
    startDate: "1992-06-16",
    street: "36 high street",
    city: "london",
    state: "Germany",
    zipCode: "23974",
    department: "department3",
    testNumber: 86,
    testBoolean: false,
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1995-06-14",
    startDate: "2013-07-27",
    street: "54 boulevard saint-germain",
    city: "lacaune",
    state: "UK",
    zipCode: "13684",
    department: "department4",
    testNumber: 34,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Smith",
    dateOfBirth: "1996-05-07",
    startDate: "2015-05-21",
    street: "76 high street",
    city: "paris",
    state: "Japan",
    zipCode: "98570",
    department: "department3",
    testNumber: 83,
    testBoolean: false,
  },
  {
    firstName: "Eve",
    lastName: "Martinez",
    dateOfBirth: "2004-10-03",
    startDate: "2025-08-24",
    street: "79 main street",
    city: "dakar",
    state: "UK",
    zipCode: "99105",
    department: "department4",
    testNumber: 61,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Jones",
    dateOfBirth: "1955-12-31",
    startDate: "1976-06-19",
    street: "94 rue du griffoul",
    city: "tombouctou",
    state: "Mali",
    zipCode: "63851",
    department: "department4",
    testNumber: 1,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Doe",
    dateOfBirth: "1951-06-27",
    startDate: "1972-05-09",
    street: "54 boulevard saint-germain",
    city: "berlin",
    state: "Spain",
    zipCode: "10080",
    department: "department4",
    testNumber: 98,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    dateOfBirth: "1959-07-14",
    startDate: "1979-09-03",
    street: "71 high street",
    city: "paris",
    state: "Germany",
    zipCode: "18484",
    department: "department3",
    testNumber: 11,
    testBoolean: false,
  },
  {
    firstName: "Charlie",
    lastName: "Miller",
    dateOfBirth: "1965-07-21",
    startDate: "1984-09-29",
    street: "22 rue du griffoul",
    city: "dakar",
    state: "USA",
    zipCode: "56951",
    department: "department1",
    testNumber: 5,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Doe",
    dateOfBirth: "1976-07-14",
    startDate: "1995-02-12",
    street: "61 rue du griffoul",
    city: "london",
    state: "Senegal",
    zipCode: "90025",
    department: "department3",
    testNumber: 29,
    testBoolean: true,
  },
  {
    firstName: "Frank",
    lastName: "Martinez",
    dateOfBirth: "1955-09-12",
    startDate: "1976-05-23",
    street: "2 rue du griffoul",
    city: "lacaune",
    state: "Japan",
    zipCode: "60063",
    department: "department1",
    testNumber: 6,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Garcia",
    dateOfBirth: "1961-01-09",
    startDate: "1977-04-07",
    street: "2 rue du griffoul",
    city: "berlin",
    state: "Spain",
    zipCode: "32246",
    department: "department4",
    testNumber: 37,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Smith",
    dateOfBirth: "1963-10-17",
    startDate: "1980-05-24",
    street: "39 avenue des champs",
    city: "lacaune",
    state: "Senegal",
    zipCode: "75766",
    department: "department3",
    testNumber: 74,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    dateOfBirth: "1953-06-17",
    startDate: "1970-11-07",
    street: "74 avenue des champs",
    city: "madrid",
    state: "Japan",
    zipCode: "50729",
    department: "department2",
    testNumber: 92,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Davis",
    dateOfBirth: "1975-12-06",
    startDate: "1995-03-08",
    street: "12 avenue des champs",
    city: "new york",
    state: "USA",
    zipCode: "28423",
    department: "department1",
    testNumber: 83,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Johnson",
    dateOfBirth: "1978-12-14",
    startDate: "1995-12-15",
    street: "63 avenue des champs",
    city: "castres",
    state: "Germany",
    zipCode: "21656",
    department: "department4",
    testNumber: 81,
    testBoolean: false,
  },
  {
    firstName: "Alice",
    lastName: "Jones",
    dateOfBirth: "1988-04-07",
    startDate: "2005-02-22",
    street: "84 high street",
    city: "castres",
    state: "France",
    zipCode: "90992",
    department: "department3",
    testNumber: 52,
    testBoolean: true,
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1975-01-05",
    startDate: "1993-09-15",
    street: "30 rue du griffoul",
    city: "berlin",
    state: "Japan",
    zipCode: "94410",
    department: "department2",
    testNumber: 38,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Davis",
    dateOfBirth: "1951-08-17",
    startDate: "1969-05-18",
    street: "48 main street",
    city: "tombouctou",
    state: "UK",
    zipCode: "89146",
    department: "department2",
    testNumber: 4,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Jones",
    dateOfBirth: "2002-10-23",
    startDate: "2023-08-15",
    street: "66 rue du griffoul",
    city: "berlin",
    state: "Japan",
    zipCode: "94041",
    department: "department1",
    testNumber: 36,
    testBoolean: false,
  },
  {
    firstName: "Eve",
    lastName: "Miller",
    dateOfBirth: "1979-10-03",
    startDate: "1996-09-06",
    street: "5 avenue des champs",
    city: "tokyo",
    state: "Mali",
    zipCode: "42310",
    department: "department4",
    testNumber: 69,
    testBoolean: true,
  },
  {
    firstName: "Hugo",
    lastName: "Miller",
    dateOfBirth: "1991-08-07",
    startDate: "2010-06-05",
    street: "67 avenue des champs",
    city: "tombouctou",
    state: "Spain",
    zipCode: "90095",
    department: "department4",
    testNumber: 98,
    testBoolean: false,
  },
  {
    firstName: "Jane",
    lastName: "Brown",
    dateOfBirth: "1955-07-04",
    startDate: "1975-09-30",
    street: "98 main street",
    city: "castres",
    state: "France",
    zipCode: "84625",
    department: "department3",
    testNumber: 66,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Garcia",
    dateOfBirth: "1960-06-30",
    startDate: "1977-05-07",
    street: "99 avenue des champs",
    city: "lacaune",
    state: "USA",
    zipCode: "27051",
    department: "department2",
    testNumber: 67,
    testBoolean: false,
  },
  {
    firstName: "Hugo",
    lastName: "Brown",
    dateOfBirth: "1956-08-10",
    startDate: "1974-11-02",
    street: "35 boulevard saint-germain",
    city: "castres",
    state: "Germany",
    zipCode: "61513",
    department: "department3",
    testNumber: 57,
    testBoolean: false,
  },
  {
    firstName: "Grace",
    lastName: "Garcia",
    dateOfBirth: "1966-10-08",
    startDate: "1985-04-24",
    street: "27 high street",
    city: "dakar",
    state: "Spain",
    zipCode: "48632",
    department: "department2",
    testNumber: 54,
    testBoolean: false,
  },
  {
    firstName: "Frank",
    lastName: "Martinez",
    dateOfBirth: "1951-01-08",
    startDate: "1968-01-15",
    street: "60 rue du griffoul",
    city: "tokyo",
    state: "UK",
    zipCode: "94615",
    department: "department2",
    testNumber: 88,
    testBoolean: false,
  },
  {
    firstName: "Charlie",
    lastName: "Williams",
    dateOfBirth: "1985-08-03",
    startDate: "2003-05-30",
    street: "9 high street",
    city: "lacaune",
    state: "UK",
    zipCode: "44111",
    department: "department4",
    testNumber: 31,
    testBoolean: false,
  },
  {
    firstName: "Grace",
    lastName: "Doe",
    dateOfBirth: "1951-09-27",
    startDate: "1972-06-28",
    street: "32 avenue des champs",
    city: "paris",
    state: "Mali",
    zipCode: "89948",
    department: "department4",
    testNumber: 97,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Martinez",
    dateOfBirth: "1975-02-26",
    startDate: "1995-08-24",
    street: "13 boulevard saint-germain",
    city: "berlin",
    state: "Japan",
    zipCode: "22675",
    department: "department3",
    testNumber: 5,
    testBoolean: false,
  },
  {
    firstName: "Eve",
    lastName: "Martinez",
    dateOfBirth: "1974-08-12",
    startDate: "1994-08-25",
    street: "29 avenue des champs",
    city: "london",
    state: "Germany",
    zipCode: "90253",
    department: "department3",
    testNumber: 58,
    testBoolean: false,
  },
  {
    firstName: "Hugo",
    lastName: "Williams",
    dateOfBirth: "1968-11-11",
    startDate: "1985-11-29",
    street: "79 rue du griffoul",
    city: "tombouctou",
    state: "Germany",
    zipCode: "98220",
    department: "department4",
    testNumber: 70,
    testBoolean: true,
  },
  {
    firstName: "John",
    lastName: "Jones",
    dateOfBirth: "1984-03-11",
    startDate: "2002-08-09",
    street: "74 avenue des champs",
    city: "madrid",
    state: "UK",
    zipCode: "14841",
    department: "department1",
    testNumber: 38,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Miller",
    dateOfBirth: "2001-12-30",
    startDate: "2022-09-04",
    street: "85 rue du griffoul",
    city: "castres",
    state: "Mali",
    zipCode: "76534",
    department: "department4",
    testNumber: 6,
    testBoolean: false,
  },
  {
    firstName: "Jane",
    lastName: "Miller",
    dateOfBirth: "1982-09-15",
    startDate: "2002-03-14",
    street: "16 boulevard saint-germain",
    city: "new york",
    state: "France",
    zipCode: "47472",
    department: "department4",
    testNumber: 41,
    testBoolean: true,
  },
  {
    firstName: "David",
    lastName: "Brown",
    dateOfBirth: "2000-08-25",
    startDate: "2019-02-15",
    street: "79 rue du griffoul",
    city: "berlin",
    state: "France",
    zipCode: "56534",
    department: "department1",
    testNumber: 89,
    testBoolean: true,
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1984-01-13",
    startDate: "2001-07-22",
    street: "28 high street",
    city: "new york",
    state: "Spain",
    zipCode: "33497",
    department: "department4",
    testNumber: 7,
    testBoolean: false,
  },
  {
    firstName: "David",
    lastName: "Davis",
    dateOfBirth: "1996-08-19",
    startDate: "2015-08-23",
    street: "73 high street",
    city: "paris",
    state: "Senegal",
    zipCode: "99435",
    department: "department1",
    testNumber: 31,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Davis",
    dateOfBirth: "1970-01-30",
    startDate: "1990-04-01",
    street: "75 rue du griffoul",
    city: "dakar",
    state: "Spain",
    zipCode: "41027",
    department: "department3",
    testNumber: 50,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Doe",
    dateOfBirth: "1983-12-15",
    startDate: "2004-08-29",
    street: "66 main street",
    city: "castres",
    state: "USA",
    zipCode: "28223",
    department: "department1",
    testNumber: 79,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Smith",
    dateOfBirth: "1983-06-15",
    startDate: "2001-12-28",
    street: "13 main street",
    city: "berlin",
    state: "Senegal",
    zipCode: "18507",
    department: "department3",
    testNumber: 78,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Miller",
    dateOfBirth: "1983-10-27",
    startDate: "2003-08-26",
    street: "2 rue du griffoul",
    city: "castres",
    state: "USA",
    zipCode: "83939",
    department: "department1",
    testNumber: 56,
    testBoolean: false,
  },
  {
    firstName: "Jane",
    lastName: "Brown",
    dateOfBirth: "1951-12-28",
    startDate: "1969-04-17",
    street: "48 rue du griffoul",
    city: "lacaune",
    state: "Senegal",
    zipCode: "83596",
    department: "department2",
    testNumber: 7,
    testBoolean: false,
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1974-06-16",
    startDate: "1991-02-04",
    street: "76 avenue des champs",
    city: "castres",
    state: "USA",
    zipCode: "80255",
    department: "department1",
    testNumber: 24,
    testBoolean: false,
  },
  {
    firstName: "David",
    lastName: "Williams",
    dateOfBirth: "1968-12-11",
    startDate: "1989-06-22",
    street: "92 avenue des champs",
    city: "tokyo",
    state: "Germany",
    zipCode: "70843",
    department: "department3",
    testNumber: 11,
    testBoolean: false,
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1995-06-12",
    startDate: "2012-10-04",
    street: "15 avenue des champs",
    city: "london",
    state: "UK",
    zipCode: "30826",
    department: "department3",
    testNumber: 75,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Doe",
    dateOfBirth: "1981-11-08",
    startDate: "2000-10-26",
    street: "84 boulevard saint-germain",
    city: "tokyo",
    state: "Mali",
    zipCode: "58222",
    department: "department1",
    testNumber: 43,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Williams",
    dateOfBirth: "1966-09-27",
    startDate: "1982-11-24",
    street: "83 boulevard saint-germain",
    city: "paris",
    state: "UK",
    zipCode: "35316",
    department: "department4",
    testNumber: 45,
    testBoolean: false,
  },
  {
    firstName: "Grace",
    lastName: "Garcia",
    dateOfBirth: "1966-12-21",
    startDate: "1986-06-25",
    street: "68 boulevard saint-germain",
    city: "dakar",
    state: "Japan",
    zipCode: "22612",
    department: "department4",
    testNumber: 73,
    testBoolean: false,
  },
  {
    firstName: "Grace",
    lastName: "Jones",
    dateOfBirth: "1978-03-15",
    startDate: "1998-03-09",
    street: "80 boulevard saint-germain",
    city: "london",
    state: "France",
    zipCode: "37689",
    department: "department1",
    testNumber: 51,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Johnson",
    dateOfBirth: "2000-08-28",
    startDate: "2018-08-22",
    street: "56 boulevard saint-germain",
    city: "berlin",
    state: "Japan",
    zipCode: "21340",
    department: "department2",
    testNumber: 13,
    testBoolean: false,
  },
  {
    firstName: "Frank",
    lastName: "Brown",
    dateOfBirth: "2006-09-29",
    startDate: "2025-10-12",
    street: "11 boulevard saint-germain",
    city: "berlin",
    state: "UK",
    zipCode: "64182",
    department: "department4",
    testNumber: 38,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: "1992-09-26",
    startDate: "2008-10-09",
    street: "44 high street",
    city: "tokyo",
    state: "Germany",
    zipCode: "43498",
    department: "department3",
    testNumber: 97,
    testBoolean: true,
  },
  {
    firstName: "Frank",
    lastName: "Garcia",
    dateOfBirth: "2001-11-07",
    startDate: "2018-05-09",
    street: "58 avenue des champs",
    city: "castres",
    state: "Japan",
    zipCode: "85200",
    department: "department1",
    testNumber: 21,
    testBoolean: false,
  },
  {
    firstName: "Eve",
    lastName: "Smith",
    dateOfBirth: "2002-10-01",
    startDate: "2019-03-24",
    street: "6 avenue des champs",
    city: "castres",
    state: "Senegal",
    zipCode: "71430",
    department: "department4",
    testNumber: 68,
    testBoolean: true,
  },
  {
    firstName: "Hugo",
    lastName: "Smith",
    dateOfBirth: "2002-04-23",
    startDate: "2022-08-10",
    street: "68 main street",
    city: "paris",
    state: "Mali",
    zipCode: "81154",
    department: "department1",
    testNumber: 83,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Johnson",
    dateOfBirth: "1969-10-07",
    startDate: "1988-12-14",
    street: "24 rue du griffoul",
    city: "tokyo",
    state: "UK",
    zipCode: "10092",
    department: "department1",
    testNumber: 53,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Davis",
    dateOfBirth: "1978-12-05",
    startDate: "1999-09-29",
    street: "28 high street",
    city: "dakar",
    state: "France",
    zipCode: "11869",
    department: "department4",
    testNumber: 48,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Davis",
    dateOfBirth: "1960-07-24",
    startDate: "1978-04-19",
    street: "44 high street",
    city: "tombouctou",
    state: "Spain",
    zipCode: "70726",
    department: "department3",
    testNumber: 65,
    testBoolean: false,
  },
  {
    firstName: "Bob",
    lastName: "Williams",
    dateOfBirth: "1993-08-08",
    startDate: "2012-04-10",
    street: "41 rue du griffoul",
    city: "london",
    state: "Japan",
    zipCode: "34152",
    department: "department1",
    testNumber: 51,
    testBoolean: false,
  },
  {
    firstName: "Charlie",
    lastName: "Smith",
    dateOfBirth: "1972-06-22",
    startDate: "1988-07-08",
    street: "63 high street",
    city: "madrid",
    state: "Senegal",
    zipCode: "99730",
    department: "department3",
    testNumber: 66,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Williams",
    dateOfBirth: "1957-11-26",
    startDate: "1977-05-11",
    street: "77 main street",
    city: "berlin",
    state: "France",
    zipCode: "48179",
    department: "department4",
    testNumber: 62,
    testBoolean: false,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: "1999-08-29",
    startDate: "2017-06-21",
    street: "80 high street",
    city: "lacaune",
    state: "Germany",
    zipCode: "25531",
    department: "department3",
    testNumber: 76,
    testBoolean: true,
  },
  {
    firstName: "Grace",
    lastName: "Smith",
    dateOfBirth: "1963-03-08",
    startDate: "1982-04-06",
    street: "64 boulevard saint-germain",
    city: "berlin",
    state: "USA",
    zipCode: "51843",
    department: "department1",
    testNumber: 84,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Smith",
    dateOfBirth: "1952-06-29",
    startDate: "1972-07-22",
    street: "20 high street",
    city: "madrid",
    state: "Germany",
    zipCode: "71262",
    department: "department1",
    testNumber: 34,
    testBoolean: true,
  },
  {
    firstName: "Hugo",
    lastName: "Johnson",
    dateOfBirth: "1989-11-10",
    startDate: "2008-10-24",
    street: "36 avenue des champs",
    city: "tombouctou",
    state: "USA",
    zipCode: "62501",
    department: "department2",
    testNumber: 52,
    testBoolean: false,
  },
  {
    firstName: "David",
    lastName: "Doe",
    dateOfBirth: "1988-12-19",
    startDate: "2007-06-05",
    street: "29 main street",
    city: "paris",
    state: "Germany",
    zipCode: "14653",
    department: "department1",
    testNumber: 24,
    testBoolean: true,
  },
  {
    firstName: "Alice",
    lastName: "Davis",
    dateOfBirth: "1960-07-21",
    startDate: "1980-02-21",
    street: "61 main street",
    city: "paris",
    state: "France",
    zipCode: "87908",
    department: "department4",
    testNumber: 83,
    testBoolean: true,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    dateOfBirth: "2003-01-09",
    startDate: "2022-07-05",
    street: "27 avenue des champs",
    city: "madrid",
    state: "UK",
    zipCode: "65033",
    department: "department4",
    testNumber: 11,
    testBoolean: true,
  },
  {
    firstName: "Eve",
    lastName: "Garcia",
    dateOfBirth: "1995-10-20",
    startDate: "2012-04-25",
    street: "58 main street",
    city: "tokyo",
    state: "UK",
    zipCode: "16788",
    department: "department4",
    testNumber: 98,
    testBoolean: false,
  },
  {
    firstName: "Charlie",
    lastName: "Garcia",
    dateOfBirth: "1981-11-26",
    startDate: "1998-12-19",
    street: "66 avenue des champs",
    city: "castres",
    state: "USA",
    zipCode: "34398",
    department: "department1",
    testNumber: 35,
    testBoolean: true,
  },
  {
    firstName: "Bob",
    lastName: "Martinez",
    dateOfBirth: "1963-08-29",
    startDate: "1983-02-24",
    street: "56 rue du griffoul",
    city: "madrid",
    state: "USA",
    zipCode: "69466",
    department: "department1",
    testNumber: 11,
    testBoolean: true,
  },
  {
    firstName: "Charlie",
    lastName: "Martinez",
    dateOfBirth: "1954-02-11",
    startDate: "1970-10-31",
    street: "12 main street",
    city: "castres",
    state: "Japan",
    zipCode: "57776",
    department: "department1",
    testNumber: 92,
    testBoolean: true,
  },
  {
    firstName: "John",
    lastName: "Johnson",
    dateOfBirth: "1970-07-01",
    startDate: "1987-09-22",
    street: "1 rue du griffoul",
    city: "new york",
    state: "Mali",
    zipCode: "56175",
    department: "department3",
    testNumber: 63,
    testBoolean: false,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    dateOfBirth: "1996-10-18",
    startDate: "2016-10-28",
    street: "96 boulevard saint-germain",
    city: "berlin",
    state: "USA",
    zipCode: "56788",
    department: "department2",
    testNumber: 11,
    testBoolean: false,
  },
  {
    firstName: "Grace",
    lastName: "Williams",
    dateOfBirth: "1966-09-22",
    startDate: "1985-05-08",
    street: "33 main street",
    city: "paris",
    state: "Japan",
    zipCode: "60017",
    department: "department2",
    testNumber: 83,
    testBoolean: false,
  },
  {
    firstName: "Frank",
    lastName: "Miller",
    dateOfBirth: "1974-11-07",
    startDate: "1992-04-20",
    street: "24 rue du griffoul",
    city: "castres",
    state: "France",
    zipCode: "59866",
    department: "department1",
    testNumber: 38,
    testBoolean: true,
  },
];
