name: Build and Publish

on:
  release:
    types:
      - published # Déclenche uniquement quand une release est publiée

jobs:
  build-and-publish:
    runs-on: self-hosted # Utilisation d'un runner local

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
          cache: "npm" # Cache les dépendances pour des builds plus rapides
          # registry-url: "https://registry.npmjs.org"

      # Étape 3: Mettre à jour la version dans package.json
      - name: Update package.json version
        id: update-version
        run: |
          $TAG_NAME = $env:GITHUB_REF -replace '^refs/tags/', ''
          Write-Host "Release tag: $TAG_NAME"
          npm version $TAG_NAME --no-git-tag-version

      # Étape 4 : Installer les dépendances nécessaires
      - name: Install dependencies
        run: npm ci

      # Étape 5 : Créer un fichier .npmrc avec le token npm
      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > $HOME/.npmrc

      # Étape 7 : Build du projet
      - name: Build project
        run: npm run build

      # Étape 8 : Publier sur npm
      - name: Publish to npm
        run: npm publish
